### ISSUE TITLE
Bug: Impossible to get first word

### ISSUE THREAD

**Issue by torsteingrindvik** [kentare/norwegian-readable-id-generator#1]
`Math.floor(Math.random() * adjektiv.length + 1)`

The least `Math.random()` returns is `0.0`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

So no matter the length of the second operand, you will get `+ 1`.
Since `Math.floor(1.0)` returns `1`, you never get index `0`.

EDIT:
TL;DR: `Math.floor(0.0 * 1000000 + 1)` is `1`.

**Comment by kentare** [comment]
fixed by commit https://github.com/kentare/norwegian-readable-id-generator/commit/c455f727df0c485a1570a55a0405c07eaf7dde09
